name: test

on:
  pull_request:
    branches: [ development, main ]

jobs:
  build:
    env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm test